-- ============================================================================
-- SCRIPT COMPLETO: DROP + CREATE + IDENTITY
-- MyTodoList API REST - Oracle Autonomous Database
--
-- INCLUYE todas las tablas que las entidades JPA esperan:
--   ESTATUS_TAREA, PRIORIDAD_TAREA, ROLES, EQUIPOS, USUARIOS,
--   SPRINTS, TAREAS, MIEMBROS_EQUIPO, COMENTARIOS_TAREA,
--   EVIDENCIAS_TAREA, LOGS_TAREA
--
-- CÓMO EJECUTAR:
--   OCI Console → Autonomous Database → chatbotdb
--   → Database Actions → SQL
--   Pegar este script completo → Run Script (F5)
-- ============================================================================

-- ============================================================================
-- 1. DROP TABLES (en orden inverso por FK)
-- ============================================================================
DROP TABLE LOGS_TAREA        CASCADE CONSTRAINTS PURGE;
DROP TABLE EVIDENCIAS_TAREA  CASCADE CONSTRAINTS PURGE;
DROP TABLE COMENTARIOS_TAREA CASCADE CONSTRAINTS PURGE;
DROP TABLE MIEMBROS_EQUIPO   CASCADE CONSTRAINTS PURGE;
DROP TABLE TAREAS            CASCADE CONSTRAINTS PURGE;
DROP TABLE SPRINTS           CASCADE CONSTRAINTS PURGE;
DROP TABLE USUARIOS          CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLES             CASCADE CONSTRAINTS PURGE;
DROP TABLE PRIORIDAD_TAREA   CASCADE CONSTRAINTS PURGE;
DROP TABLE ESTATUS_TAREA     CASCADE CONSTRAINTS PURGE;
DROP TABLE EQUIPOS           CASCADE CONSTRAINTS PURGE;

-- ============================================================================
-- 2. CREATE TABLES CON IDENTITY
-- ============================================================================

CREATE TABLE ESTATUS_TAREA (
    ID_ESTATUS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE     VARCHAR2(100),
    ORDEN      NUMBER
);

CREATE TABLE PRIORIDAD_TAREA (
    ID_PRIORIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE       VARCHAR2(100),
    ORDEN        NUMBER
);

CREATE TABLE ROLES (
    ID_ROL      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100),
    DESCRIPCION VARCHAR2(255)
);

CREATE TABLE EQUIPOS (
    ID_EQUIPO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE    VARCHAR2(100)
);

CREATE TABLE USUARIOS (
    ID_USUARIO             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_INTEGRATION_USUARIO VARCHAR2(100) UNIQUE,
    NOMBRE_USUARIO         VARCHAR2(100),
    NOMBRE_COMPLETO        VARCHAR2(200),
    ID_ROL                 NUMBER,
    CREADO_EN              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE SPRINTS (
    ID_SPRINT  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE     VARCHAR2(100)  NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN    DATE,
    ACTIVO       NUMBER(1) DEFAULT 0,
    CREADO_EN    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TAREAS (
    ID_TAREA            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO              VARCHAR2(200),
    DESCRIPCION         VARCHAR2(500),
    ID_ESTATUS          NUMBER,
    ID_PRIORIDAD        NUMBER,
    ID_USUARIO_CREADOR  NUMBER,
    ID_USUARIO_ASIGNADO NUMBER,
    FECHA_VENCIMIENTO   DATE,
    NULL_FIELD          VARCHAR2(50),
    HORAS_ESTIMADAS     NUMBER,
    HORAS_REALES        NUMBER,
    ID_SPRINT           NUMBER,
    CREADO_EN           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN      TIMESTAMP,
    CONSTRAINT FK_TAREA_ESTATUS   FOREIGN KEY (ID_ESTATUS)          REFERENCES ESTATUS_TAREA(ID_ESTATUS),
    CONSTRAINT FK_TAREA_PRIORIDAD FOREIGN KEY (ID_PRIORIDAD)        REFERENCES PRIORIDAD_TAREA(ID_PRIORIDAD),
    CONSTRAINT FK_TAREA_CREADOR   FOREIGN KEY (ID_USUARIO_CREADOR)  REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_TAREA_ASIGNADO  FOREIGN KEY (ID_USUARIO_ASIGNADO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_TAREA_SPRINT    FOREIGN KEY (ID_SPRINT)           REFERENCES SPRINTS(ID_SPRINT)
);

CREATE TABLE MIEMBROS_EQUIPO (
    ID_EQUIPO  NUMBER,
    ID_USUARIO NUMBER,
    SE_UNIO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_EQUIPO, ID_USUARIO),
    CONSTRAINT FK_ME_EQUIPO  FOREIGN KEY (ID_EQUIPO)  REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT FK_ME_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE COMENTARIOS_TAREA (
    ID_COMENTARIO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TAREA         NUMBER,
    ID_USUARIO_AUTOR NUMBER,
    CUERPO           VARCHAR2(1000),
    CREADO_EN        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMENT_TAREA   FOREIGN KEY (ID_TAREA)          REFERENCES TAREAS(ID_TAREA),
    CONSTRAINT FK_COMENT_USUARIO FOREIGN KEY (ID_USUARIO_AUTOR)  REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE EVIDENCIAS_TAREA (
    ID_EVIDENCIA     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TAREA         NUMBER,
    ID_USUARIO_SUBIO NUMBER,
    URL_ARCHIVO      VARCHAR2(500),
    NOTA             VARCHAR2(500),
    CREADO_EN        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_EVIDENCIA_TAREA   FOREIGN KEY (ID_TAREA)           REFERENCES TAREAS(ID_TAREA),
    CONSTRAINT FK_EVIDENCIA_USUARIO FOREIGN KEY (ID_USUARIO_SUBIO)   REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE LOGS_TAREA (
    ID_LOG             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TAREA           NUMBER,
    ID_USUARIO         NUMBER,
    ID_ESTATUS_ORIGEN  NUMBER,
    ID_ESTATUS_DESTINO NUMBER,
    MENSAJE            VARCHAR2(500),
    CREADO_EN          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOG_TAREA   FOREIGN KEY (ID_TAREA)   REFERENCES TAREAS(ID_TAREA),
    CONSTRAINT FK_LOG_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- ============================================================================
-- VERIFICACIÓN
-- ============================================================================
SELECT TABLE_NAME, STATUS
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'ESTATUS_TAREA','PRIORIDAD_TAREA','ROLES','EQUIPOS',
    'USUARIOS','SPRINTS','TAREAS','MIEMBROS_EQUIPO',
    'COMENTARIOS_TAREA','EVIDENCIAS_TAREA','LOGS_TAREA'
)
ORDER BY TABLE_NAME;
