-- ============================================================================
-- SQL SCRIPT - INITIAL DATA FOR PARALLEL TESTING
-- MyTodoList REST API - Oracle Autonomous Database
--
-- Uses PL/SQL with RETURNING INTO to capture IDs generated by Hibernate
-- sequences, without conflicts with subsequent insertions.
--
-- HOW TO RUN:
--   OCI Console → Autonomous Database → chatbotdb
--   → Database Actions → SQL
--   Paste this complete script → Run Script (F5)
--   Enable first: View → DBMS Output (to see messages)
--
-- NOTE: All table references are explicitly qualified with EQUIPO51. so this
-- script is safe to run as any database user (ADMIN, EQUIPO51, etc.).
-- The app connects as EQUIPO51, so all tables live in the EQUIPO51 schema.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
  -- Roles
  v_rol_admin     NUMBER;
  v_rol_developer NUMBER;

  -- Statuses
  v_est_pendiente  NUMBER;
  v_est_progreso   NUMBER;
  v_est_completada NUMBER;

  -- Priorities
  v_pri_baja  NUMBER;
  v_pri_media NUMBER;
  v_pri_alta  NUMBER;

  -- Teams
  v_eq_alpha NUMBER;
  v_eq_beta  NUMBER;
  v_eq_gamma NUMBER;

  -- Users
  v_usr_gabriel   NUMBER;
  v_usr_rutilo    NUMBER;
  v_usr_grecia    NUMBER;
  v_usr_eugenio   NUMBER;
  v_usr_elian     NUMBER;
  v_usr_alejandro NUMBER;

  -- Tasks
  v_tar_login    NUMBER;
  v_tar_bd       NUMBER;
  v_tar_cicd     NUMBER;
  v_tar_telegram NUMBER;
  v_tar_swagger  NUMBER;

BEGIN

  -- ============================================================================
  -- PRIOR CLEANUP
  -- ============================================================================
  DELETE FROM EQUIPO51.LOGS_TAREA;
  DELETE FROM EQUIPO51.EVIDENCIAS_TAREA;
  DELETE FROM EQUIPO51.COMENTARIOS_TAREA;
  DELETE FROM EQUIPO51.MIEMBROS_EQUIPO;
  DELETE FROM EQUIPO51.TAREAS;
  DELETE FROM EQUIPO51.USUARIOS;
  DELETE FROM EQUIPO51.PRIORIDAD_TAREA;
  DELETE FROM EQUIPO51.ESTATUS_TAREA;
  DELETE FROM EQUIPO51.EQUIPOS;
  DELETE FROM EQUIPO51.ROLES;
  DBMS_OUTPUT.PUT_LINE('Cleanup completed.');


  -- ============================================================================
  -- 1. ROLES
  -- ============================================================================
  INSERT INTO EQUIPO51.ROLES (NOMBRE, DESCRIPCION)
  VALUES ('Admin', 'Full system control')
  RETURNING ID_ROL INTO v_rol_admin;

  INSERT INTO EQUIPO51.ROLES (NOMBRE, DESCRIPCION)
  VALUES ('Developer', 'Management of own tasks and code review')
  RETURNING ID_ROL INTO v_rol_developer;

  DBMS_OUTPUT.PUT_LINE('Roles: Admin=' || v_rol_admin || ', Developer=' || v_rol_developer);


  -- ============================================================================
  -- 2. TASK STATUSES
  -- ============================================================================
  INSERT INTO EQUIPO51.ESTATUS_TAREA (NOMBRE, ORDEN) VALUES ('Pending',     1) RETURNING ID_ESTATUS INTO v_est_pendiente;
  INSERT INTO EQUIPO51.ESTATUS_TAREA (NOMBRE, ORDEN) VALUES ('In Progress', 2) RETURNING ID_ESTATUS INTO v_est_progreso;
  INSERT INTO EQUIPO51.ESTATUS_TAREA (NOMBRE, ORDEN) VALUES ('Completed',   3) RETURNING ID_ESTATUS INTO v_est_completada;

  DBMS_OUTPUT.PUT_LINE('Statuses: Pending=' || v_est_pendiente || ', In Progress=' || v_est_progreso || ', Completed=' || v_est_completada);


  -- ============================================================================
  -- 3. PRIORITIES
  -- ============================================================================
  INSERT INTO EQUIPO51.PRIORIDAD_TAREA (NOMBRE, ORDEN) VALUES ('Low',    1) RETURNING ID_PRIORIDAD INTO v_pri_baja;
  INSERT INTO EQUIPO51.PRIORIDAD_TAREA (NOMBRE, ORDEN) VALUES ('Medium', 2) RETURNING ID_PRIORIDAD INTO v_pri_media;
  INSERT INTO EQUIPO51.PRIORIDAD_TAREA (NOMBRE, ORDEN) VALUES ('High',   3) RETURNING ID_PRIORIDAD INTO v_pri_alta;

  DBMS_OUTPUT.PUT_LINE('Priorities: Low=' || v_pri_baja || ', Medium=' || v_pri_media || ', High=' || v_pri_alta);


  -- ============================================================================
  -- 4. TEAMS
  -- ============================================================================
  INSERT INTO EQUIPO51.EQUIPOS (NOMBRE) VALUES ('Team Alpha') RETURNING ID_EQUIPO INTO v_eq_alpha;
  INSERT INTO EQUIPO51.EQUIPOS (NOMBRE) VALUES ('Team Beta')  RETURNING ID_EQUIPO INTO v_eq_beta;
  INSERT INTO EQUIPO51.EQUIPOS (NOMBRE) VALUES ('Team Gamma') RETURNING ID_EQUIPO INTO v_eq_gamma;

  DBMS_OUTPUT.PUT_LINE('Teams: Alpha=' || v_eq_alpha || ', Beta=' || v_eq_beta || ', Gamma=' || v_eq_gamma);


  -- ============================================================================
  -- 5. USERS
  -- ============================================================================
  INSERT INTO EQUIPO51.USUARIOS (ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
  VALUES ('TG_001', 'gabriel.admin', 'Gabriel Administrator', v_rol_admin, SYSDATE)
  RETURNING ID_USUARIO INTO v_usr_gabriel;

  INSERT INTO EQUIPO51.USUARIOS (ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
  VALUES ('TG_002', 'rutilo.dev', 'Rutilo Developer', v_rol_developer, SYSDATE)
  RETURNING ID_USUARIO INTO v_usr_rutilo;

  INSERT INTO EQUIPO51.USUARIOS (ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
  VALUES ('TG_003', 'grecia.dev', 'Grecia Developer', v_rol_developer, SYSDATE)
  RETURNING ID_USUARIO INTO v_usr_grecia;

  INSERT INTO EQUIPO51.USUARIOS (ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
  VALUES ('TG_004', 'eugenio.dev', 'Eugenio Developer', v_rol_developer, SYSDATE)
  RETURNING ID_USUARIO INTO v_usr_eugenio;

  INSERT INTO EQUIPO51.USUARIOS (ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
  VALUES ('TG_005', 'elian.dev', 'Elian Developer', v_rol_developer, SYSDATE)
  RETURNING ID_USUARIO INTO v_usr_elian;

  INSERT INTO EQUIPO51.USUARIOS (ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
  VALUES ('TG_006', 'alejandro.dev', 'Alejandro Developer', v_rol_developer, SYSDATE)
  RETURNING ID_USUARIO INTO v_usr_alejandro;

  DBMS_OUTPUT.PUT_LINE('Users: gabriel=' || v_usr_gabriel || ', rutilo=' || v_usr_rutilo ||
                       ', grecia=' || v_usr_grecia || ', eugenio=' || v_usr_eugenio ||
                       ', elian=' || v_usr_elian || ', alejandro=' || v_usr_alejandro);


  -- ============================================================================
  -- 6. TASKS
  -- ============================================================================
  INSERT INTO EQUIPO51.TAREAS (TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD,
                      ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
  VALUES ('Implement JWT login', 'Create login screen and authentication endpoint with JWT',
          v_est_pendiente, v_pri_alta, v_usr_gabriel, v_usr_rutilo,
          TO_DATE('2026-04-30','YYYY-MM-DD'), SYSDATE, SYSDATE)
  RETURNING ID_TAREA INTO v_tar_login;

  INSERT INTO EQUIPO51.TAREAS (TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD,
                      ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
  VALUES ('Design database', 'Model entities and relationships in Oracle ADB',
          v_est_progreso, v_pri_media, v_usr_gabriel, v_usr_grecia,
          TO_DATE('2026-04-25','YYYY-MM-DD'), SYSDATE, SYSDATE)
  RETURNING ID_TAREA INTO v_tar_bd;

  INSERT INTO EQUIPO51.TAREAS (TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD,
                      ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
  VALUES ('Configure CI/CD pipeline', 'Automated deployment pipeline on OCI',
          v_est_pendiente, v_pri_media, v_usr_rutilo, v_usr_eugenio,
          TO_DATE('2026-05-10','YYYY-MM-DD'), SYSDATE, SYSDATE)
  RETURNING ID_TAREA INTO v_tar_cicd;

  INSERT INTO EQUIPO51.TAREAS (TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD,
                      ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
  VALUES ('Integrate Telegram bot', 'Connect the bot with the REST API endpoints',
          v_est_progreso, v_pri_alta, v_usr_gabriel, v_usr_elian,
          TO_DATE('2026-05-05','YYYY-MM-DD'), SYSDATE, SYSDATE)
  RETURNING ID_TAREA INTO v_tar_telegram;

  INSERT INTO EQUIPO51.TAREAS (TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD,
                      ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
  VALUES ('Document API with Swagger', 'Create complete documentation for all endpoints',
          v_est_completada, v_pri_baja, v_usr_rutilo, v_usr_alejandro,
          TO_DATE('2026-04-20','YYYY-MM-DD'), SYSDATE, SYSDATE)
  RETURNING ID_TAREA INTO v_tar_swagger;

  DBMS_OUTPUT.PUT_LINE('Tasks: login=' || v_tar_login || ', bd=' || v_tar_bd ||
                       ', cicd=' || v_tar_cicd || ', telegram=' || v_tar_telegram ||
                       ', swagger=' || v_tar_swagger);


  -- ============================================================================
  -- 7. TEAM MEMBERS
  -- ============================================================================
  INSERT INTO EQUIPO51.MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN) VALUES (v_eq_alpha, v_usr_gabriel,   SYSDATE);
  INSERT INTO EQUIPO51.MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN) VALUES (v_eq_alpha, v_usr_rutilo,    SYSDATE);
  INSERT INTO EQUIPO51.MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN) VALUES (v_eq_alpha, v_usr_grecia,    SYSDATE);
  INSERT INTO EQUIPO51.MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN) VALUES (v_eq_beta,  v_usr_eugenio,   SYSDATE);
  INSERT INTO EQUIPO51.MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN) VALUES (v_eq_beta,  v_usr_elian,     SYSDATE);
  INSERT INTO EQUIPO51.MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN) VALUES (v_eq_gamma, v_usr_alejandro, SYSDATE);
  DBMS_OUTPUT.PUT_LINE('Team members inserted: 6');


  -- ============================================================================
  -- 8. TASK COMMENTS
  -- ============================================================================
  INSERT INTO EQUIPO51.COMENTARIOS_TAREA (ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
  VALUES (v_tar_login, v_usr_rutilo, 'I started with the base JWT structure. Do we use RS256 or HS256?', SYSDATE);

  INSERT INTO EQUIPO51.COMENTARIOS_TAREA (ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
  VALUES (v_tar_login, v_usr_gabriel, 'We use HS256 with a 7-day refresh token and 1-hour access token.', SYSDATE);

  INSERT INTO EQUIPO51.COMENTARIOS_TAREA (ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
  VALUES (v_tar_bd, v_usr_grecia, 'The ER diagram is ready. We need to review the constraints.', SYSDATE);

  INSERT INTO EQUIPO51.COMENTARIOS_TAREA (ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
  VALUES (v_tar_telegram, v_usr_elian, 'Bot connected. Still need to implement the /done and /list commands.', SYSDATE);

  INSERT INTO EQUIPO51.COMENTARIOS_TAREA (ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
  VALUES (v_tar_cicd, v_usr_eugenio, 'Pipeline configured in GitHub Actions. Missing the deploy to OCI.', SYSDATE);

  INSERT INTO EQUIPO51.COMENTARIOS_TAREA (ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
  VALUES (v_tar_swagger, v_usr_alejandro, 'Documentation completed and deployed at /swagger-ui.html.', SYSDATE);

  DBMS_OUTPUT.PUT_LINE('Comments inserted: 6');


  -- ============================================================================
  -- 9. TASK EVIDENCE
  -- ============================================================================
  INSERT INTO EQUIPO51.EVIDENCIAS_TAREA (ID_TAREA, ID_USUARIO_SUBIO, URL_ARCHIVO, NOTA, CREADO_EN)
  VALUES (v_tar_login, v_usr_rutilo,
          'https://storage.oracle.com/evidencias/login-jwt-screenshot.png',
          'Screenshot of login working with valid token', SYSDATE);

  INSERT INTO EQUIPO51.EVIDENCIAS_TAREA (ID_TAREA, ID_USUARIO_SUBIO, URL_ARCHIVO, NOTA, CREADO_EN)
  VALUES (v_tar_bd, v_usr_grecia,
          'https://storage.oracle.com/evidencias/diagrama_er_v2.png',
          'ER diagram version 2.0 reviewed', SYSDATE);

  INSERT INTO EQUIPO51.EVIDENCIAS_TAREA (ID_TAREA, ID_USUARIO_SUBIO, URL_ARCHIVO, NOTA, CREADO_EN)
  VALUES (v_tar_cicd, v_usr_eugenio,
          'https://storage.oracle.com/evidencias/pipeline-success.png',
          'Green build in GitHub Actions', SYSDATE);

  INSERT INTO EQUIPO51.EVIDENCIAS_TAREA (ID_TAREA, ID_USUARIO_SUBIO, URL_ARCHIVO, NOTA, CREADO_EN)
  VALUES (v_tar_telegram, v_usr_elian,
          'https://storage.oracle.com/evidencias/bot-telegram-demo.mp4',
          'Video of the bot responding to commands', SYSDATE);

  INSERT INTO EQUIPO51.EVIDENCIAS_TAREA (ID_TAREA, ID_USUARIO_SUBIO, URL_ARCHIVO, NOTA, CREADO_EN)
  VALUES (v_tar_swagger, v_usr_alejandro,
          'https://storage.oracle.com/evidencias/swagger-docs.pdf',
          'PDF exported from the complete Swagger documentation', SYSDATE);

  DBMS_OUTPUT.PUT_LINE('Evidence inserted: 5');


  -- ============================================================================
  -- 10. TASK CHANGE LOGS
  -- ============================================================================
  INSERT INTO EQUIPO51.LOGS_TAREA (ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
  VALUES (v_tar_login, v_usr_gabriel, v_est_pendiente, v_est_progreso,
          'Task started by the team', SYSDATE);

  INSERT INTO EQUIPO51.LOGS_TAREA (ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
  VALUES (v_tar_bd, v_usr_grecia, v_est_pendiente, v_est_progreso,
          'Start of database schema design', SYSDATE);

  INSERT INTO EQUIPO51.LOGS_TAREA (ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
  VALUES (v_tar_swagger, v_usr_alejandro, v_est_progreso, v_est_completada,
          'Documentation finalized and approved', SYSDATE);

  INSERT INTO EQUIPO51.LOGS_TAREA (ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
  VALUES (v_tar_cicd, v_usr_eugenio, v_est_pendiente, v_est_progreso,
          'Base pipeline configured, missing integration with OCI', SYSDATE);

  INSERT INTO EQUIPO51.LOGS_TAREA (ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
  VALUES (v_tar_telegram, v_usr_elian, v_est_pendiente, v_est_progreso,
          'Bot registered and connected to endpoints', SYSDATE);

  DBMS_OUTPUT.PUT_LINE('Logs inserted: 5');


  -- ============================================================================
  -- FINAL COMMIT
  -- ============================================================================
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('===== SCRIPT COMPLETED SUCCESSFULLY =====');

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
    RAISE;
END;
/


-- ============================================================================
-- FINAL VERIFICATION (run after the PL/SQL block)
-- ============================================================================
SELECT 'ROLES'             AS TABLA, COUNT(*) AS TOTAL FROM EQUIPO51.ROLES             UNION ALL
SELECT 'ESTATUS_TAREA',              COUNT(*)           FROM EQUIPO51.ESTATUS_TAREA    UNION ALL
SELECT 'PRIORIDAD_TAREA',            COUNT(*)           FROM EQUIPO51.PRIORIDAD_TAREA  UNION ALL
SELECT 'EQUIPOS',                    COUNT(*)           FROM EQUIPO51.EQUIPOS           UNION ALL
SELECT 'USUARIOS',                   COUNT(*)           FROM EQUIPO51.USUARIOS          UNION ALL
SELECT 'TAREAS',                     COUNT(*)           FROM EQUIPO51.TAREAS            UNION ALL
SELECT 'MIEMBROS_EQUIPO',            COUNT(*)           FROM EQUIPO51.MIEMBROS_EQUIPO   UNION ALL
SELECT 'COMENTARIOS_TAREA',          COUNT(*)           FROM EQUIPO51.COMENTARIOS_TAREA UNION ALL
SELECT 'EVIDENCIAS_TAREA',           COUNT(*)           FROM EQUIPO51.EVIDENCIAS_TAREA  UNION ALL
SELECT 'LOGS_TAREA',                 COUNT(*)           FROM EQUIPO51.LOGS_TAREA;

-- EXPECTED RESULT:
-- ROLES              2
-- ESTATUS_TAREA      3
-- PRIORIDAD_TAREA    3
-- EQUIPOS            3
-- USUARIOS           6
-- TAREAS             5
-- MIEMBROS_EQUIPO    6
-- COMENTARIOS_TAREA  6
-- EVIDENCIAS_TAREA   5
-- LOGS_TAREA         5


-- ============================================================================
-- GENERATED IDs (run to see which IDs were stored in the database)
-- ============================================================================
SELECT 'gabriel.admin' AS USUARIO, ID_USUARIO FROM EQUIPO51.USUARIOS WHERE NOMBRE_USUARIO = 'gabriel.admin' UNION ALL
SELECT 'rutilo.dev',               ID_USUARIO FROM EQUIPO51.USUARIOS WHERE NOMBRE_USUARIO = 'rutilo.dev'    UNION ALL
SELECT 'grecia.dev',               ID_USUARIO FROM EQUIPO51.USUARIOS WHERE NOMBRE_USUARIO = 'grecia.dev'    UNION ALL
SELECT 'eugenio.dev',              ID_USUARIO FROM EQUIPO51.USUARIOS WHERE NOMBRE_USUARIO = 'eugenio.dev'   UNION ALL
SELECT 'elian.dev',                ID_USUARIO FROM EQUIPO51.USUARIOS WHERE NOMBRE_USUARIO = 'elian.dev'     UNION ALL
SELECT 'alejandro.dev',            ID_USUARIO FROM EQUIPO51.USUARIOS WHERE NOMBRE_USUARIO = 'alejandro.dev';
