package com.springboot.MyTodoList.dto;

import lombok.Value;

/**
 * Immutable response from the AI agent to the chat endpoint.
 */
@Value
public class ChatResponse {

    /** Text of the response generated by the agent. */
    String respuesta;
}
