# Dialecto para Oracle Cloud
spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect

# CONFIGURACIÓN DE CREDENCIALES
# Nota: Se usa ./wallet porque la carpeta está en la raíz de tu proyecto
spring.datasource.url=jdbc:oracle:thin:@ChatbotDB_high?TNS_ADMIN=./wallet
spring.datasource.username=ADMIN
spring.datasource.password=Equipo51_105

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Propiedades de UCP (Universal Connection Pool)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=ChatbotPool
spring.datasource.oracleucp.initial-pool-size=5
spring.datasource.oracleucp.min-pool-size=5
spring.datasource.oracleucp.max-pool-size=10

## Propiedades de Logging (Consola de depuración)
logging.level.root=info
logging.file.name=logs.log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

## Configuración del Bot de Telegram
telegram.bot.token=8285598659:AAEpxbJZIaUtWmgvuVn4Qr5Ep7XY_WfjlH4
telegram.bot.name=Pepsipepinobot

## Configuración de Inteligencia Artificial (DeepSeek)
deepseek.api.key=sk-blablabla
deepseek.api.url=https://api.deepseek.com/v1/chat/completions