# ============================================================================
# ORACLE DATABASE CONFIGURATION (ADB - Autonomous Database)
# Nota: Configurado en OracleDataSourceConfig.java
# ============================================================================
# spring.datasource.url=jdbc:oracle:thin:@reacttododm0rc_high
# spring.datasource.username=ADMIN
# spring.datasource.password=Equipo51_105

# ============================================================================
# JPA / HIBERNATE CONFIGURATION
# ============================================================================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## Propiedades de Logging (Consola de depuración)
logging.level.root=info
logging.file.name=logs.log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

## Spring Security (credenciales fijas para desarrollo/Postman)
spring.security.user.name=admin
spring.security.user.password=admin123

## Configuración del Bot de Telegram
telegram.bot.token=8611801334:AAHsDArpy-7k593SUx3Qx2ehBiyASlaY1gk
telegram.bot.name=Eq51_bot

## Configuración de Inteligencia Artificial (DeepSeek)
deepseek.api.key=sk-blablabla
deepseek.api.url=https://api.deepseek.com/v1/chat/completions