-- Test Data Script for Database Insertion
-- This script creates test data to validate the database structure

-- 1. Insert Task Statuses
INSERT INTO ESTATUS_TAREA (ID_ESTATUS, NOMBRE, ORDEN) VALUES (1, 'Pending', 1);
INSERT INTO ESTATUS_TAREA (ID_ESTATUS, NOMBRE, ORDEN) VALUES (2, 'In Progress', 2);
INSERT INTO ESTATUS_TAREA (ID_ESTATUS, NOMBRE, ORDEN) VALUES (3, 'Completed', 3);
INSERT INTO ESTATUS_TAREA (ID_ESTATUS, NOMBRE, ORDEN) VALUES (4, 'Cancelled', 4);

-- 2. Insert Priorities
INSERT INTO PRIORIDAD_TAREA (ID_PRIORIDAD, NOMBRE, ORDEN) VALUES (1, 'Low', 1);
INSERT INTO PRIORIDAD_TAREA (ID_PRIORIDAD, NOMBRE, ORDEN) VALUES (2, 'Medium', 2);
INSERT INTO PRIORIDAD_TAREA (ID_PRIORIDAD, NOMBRE, ORDEN) VALUES (3, 'High', 3);
INSERT INTO PRIORIDAD_TAREA (ID_PRIORIDAD, NOMBRE, ORDEN) VALUES (4, 'Critical', 4);

-- 3. Insert Roles
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (1, 'Admin', 'System Administrator');
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (2, 'Gerente', 'Project Manager');
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (3, 'Desarrollador', 'Software Developer');
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (4, 'QA', 'Quality Analyst');

-- 4. Insert Teams
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE) VALUES (1, 'Backend Development');
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE) VALUES (2, 'Frontend Development');
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE) VALUES (3, 'QA Team');
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE) VALUES (4, 'DevOps Team');

-- 5. Insert Users
INSERT INTO USUARIOS (ID_USUARIO, ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
VALUES (1, 'USR001', 'admin_user', 'Juan Carlos Pérez', 1, CURRENT_TIMESTAMP);

INSERT INTO USUARIOS (ID_USUARIO, ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
VALUES (2, 'USR002', 'gerente_pm', 'María García López', 2, CURRENT_TIMESTAMP);

INSERT INTO USUARIOS (ID_USUARIO, ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
VALUES (3, 'USR003', 'dev_java', 'Roberto Ramírez Torres', 3, CURRENT_TIMESTAMP);

INSERT INTO USUARIOS (ID_USUARIO, ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
VALUES (4, 'USR004', 'dev_react', 'Sofia Martínez González', 3, CURRENT_TIMESTAMP);

INSERT INTO USUARIOS (ID_USUARIO, ID_INTEGRATION_USUARIO, NOMBRE_USUARIO, NOMBRE_COMPLETO, ID_ROL, CREADO_EN)
VALUES (5, 'USR005', 'qa_analyst', 'Carlos López Fernández', 4, CURRENT_TIMESTAMP);

-- 6. Insert Tasks
INSERT INTO TAREAS (ID_TAREA, TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD, ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
VALUES (1, 'Implement Users API', 'Create REST endpoints for user management', 2, 3, 2, 3, TO_DATE('2026-05-15', 'YYYY-MM-DD'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TAREAS (ID_TAREA, TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD, ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
VALUES (2, 'Design Dashboard Interface', 'Create mockups and React components for the dashboard', 1, 3, 2, 4, TO_DATE('2026-05-20', 'YYYY-MM-DD'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TAREAS (ID_TAREA, TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD, ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
VALUES (3, 'Write Unit Tests', 'Develop tests for the service layer', 1, 2, 2, 5, TO_DATE('2026-05-10', 'YYYY-MM-DD'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TAREAS (ID_TAREA, TITULO, DESCRIPCION, ID_ESTATUS, ID_PRIORIDAD, ID_USUARIO_CREADOR, ID_USUARIO_ASIGNADO, FECHA_VENCIMIENTO, CREADO_EN, ACTUALIZADO_EN)
VALUES (4, 'Document API', 'Generate complete Swagger documentation', 3, 1, 3, 3, TO_DATE('2026-04-30', 'YYYY-MM-DD'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 7. Insert Team Members
INSERT INTO MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN)
VALUES (1, 1, CURRENT_TIMESTAMP);

INSERT INTO MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN)
VALUES (1, 3, CURRENT_TIMESTAMP);

INSERT INTO MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN)
VALUES (2, 4, CURRENT_TIMESTAMP);

INSERT INTO MIEMBROS_EQUIPO (ID_EQUIPO, ID_USUARIO, SE_UNIO_EN)
VALUES (3, 5, CURRENT_TIMESTAMP);

-- 8. Insert Task Comments
INSERT INTO COMENTARIOS_TAREA (ID_COMENTARIO, ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
VALUES (1, 1, 3, 'I have completed the base structure of the API', CURRENT_TIMESTAMP);

INSERT INTO COMENTARIOS_TAREA (ID_COMENTARIO, ID_TAREA, ID_USUARIO_AUTOR, CUERPO, CREADO_EN)
VALUES (2, 1, 2, 'Excellent work, we need to add validations', CURRENT_TIMESTAMP);

-- 9. Insert Task Evidence
INSERT INTO EVIDENCIAS_TAREA (ID_EVIDENCIA, ID_TAREA, ID_USUARIO_SUBIO, URL_ARCHIVO, NOTA, CREADO_EN)
VALUES (1, 4, 3, '/files/API_Documentation_v1.pdf', 'Complete documentation generated automatically', CURRENT_TIMESTAMP);

-- 10. Insert Task Logs (Change audit)
INSERT INTO LOGS_TAREA (ID_LOG, ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
VALUES (1, 1, 2, 1, 2, 'Task moved to In Progress', CURRENT_TIMESTAMP);

INSERT INTO LOGS_TAREA (ID_LOG, ID_TAREA, ID_USUARIO, ID_ESTATUS_ORIGEN, ID_ESTATUS_DESTINO, MENSAJE, CREADO_EN)
VALUES (2, 4, 3, 2, 3, 'Task completed', CURRENT_TIMESTAMP);

-- Commit changes
COMMIT;

-- Verify inserted data
SELECT 'Total Statuses' AS TABLA, COUNT(*) AS CANTIDAD FROM ESTATUS_TAREA
UNION ALL
SELECT 'Total Priorities', COUNT(*) FROM PRIORIDAD_TAREA
UNION ALL
SELECT 'Total Roles', COUNT(*) FROM ROLES
UNION ALL
SELECT 'Total Teams', COUNT(*) FROM EQUIPOS
UNION ALL
SELECT 'Total Users', COUNT(*) FROM USUARIOS
UNION ALL
SELECT 'Total Tasks', COUNT(*) FROM TAREAS
UNION ALL
SELECT 'Total Team Members', COUNT(*) FROM MIEMBROS_EQUIPO
UNION ALL
SELECT 'Total Comments', COUNT(*) FROM COMENTARIOS_TAREA
UNION ALL
SELECT 'Total Evidence', COUNT(*) FROM EVIDENCIAS_TAREA
UNION ALL
SELECT 'Total Logs', COUNT(*) FROM LOGS_TAREA;
