apiVersion: v1
kind: Service
metadata:
  name: todolistapp-springboot-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: todolistapp-springboot
---
apiVersion: v1
kind: Service
metadata:
  name: todolistapp-backend-router
spec:
  selector:
    app: todolistapp-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp-springboot-deployment
spec:
  selector:
    matchLabels:
      app: todolistapp-springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: todolistapp-springboot
        version: v1
    spec:
      containers:
        - name: todolistapp-springboot
          image: "%DOCKER_REGISTRY%/todolistapp-springboot:0.1"
          imagePullPolicy: Always
          env:
            - name: ORACLE_DB_USERNAME
              value: "EQUIPO51"
            - name: DB_URL
              value: "jdbc:oracle:thin:@%TODO_PDB_NAME%_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: WALLET_PATH
              value: "/mtdrworkshop/creds"
            - name: TNS_ADMIN
              value: "/mtdrworkshop/creds"
            - name: OCI_REGION
              value: "%OCI_REGION%"
            - name: ORACLE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: false
            - name: SPRING_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frontendadmin
                  key: password
                  optional: false
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: telegram-bot-token
                  optional: false
            - name: DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: deepseek-api-key
                  optional: true
            - name: ui_username
              value: "%UI_USERNAME%"
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
              name: http
      restartPolicy: Always
      imagePullSecrets:
        - name: ocir-secret
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: todolistapp-springboot
---
