apiVersion: v1
kind: Service
metadata:
  name: todolistapp-springboot-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: todolistapp-springboot
---
apiVersion: v1
kind: Service
metadata:
  name: todolistapp-backend-router
spec:
  selector:
    app: todolistapp-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp-springboot-deployment
spec:
  selector:
    matchLabels:
      app: todolistapp-springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: todolistapp-springboot
        version: v1
    spec:
      containers:
        - name: todolistapp-springboot
          image: '%DOCKER_REGISTRY%/todolistapp-springboot:0.1'
          imagePullPolicy: Always
          env:
            - name: SPRING_ADMIN_PASSWORD
              value: "None0001"
            - name: TELEGRAM_BOT_TOKEN
              value: "8611801334:AAHsDArpy-7k593SUx3Qx2ehBiyASlaY1gk"
            - name: ORACLE_DB_USERNAME
              value: "admin"
            - name: ORACLE_DB_PASSWORD
              value: "gWGa#BR%9@1peRbN"
            - name: WALLET_PATH
              value: "/mtdrworkshop/creds"
            - name: TNS_ADMIN
              value: "/mtdrworkshop/creds"
            - name: DEEPSEEK_API_KEY
              value: "placeholder"
            - name: db_user
              value: "admin"
            - name: db_url
              value: "jdbc:oracle:thin:@chatbotdb_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: todo.table.name
              value: "todoitem"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "%OCI_REGION%"
            - name: ui_username
              value: "%UI_USERNAME%"
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: ocir-secret
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: todolistapp-springboot