package com.springboot.MyTodoList.controller;

import com.springboot.MyTodoList.agent.AgentOrchestrator;
import com.springboot.MyTodoList.dto.ChatRequest;
import com.springboot.MyTodoList.dto.ChatResponse;
import jakarta.servlet.http.HttpSession;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * REST controller for the conversational assistant.
 * Exposes the POST /api/asistente/chat endpoint that receives a user message
 * and returns the response generated by the AgentOrchestrator.
 *
 * Maintains the LLM conversation history per HTTP session via
 * {@link HttpSession}, enabling multi-turn responses with context.
 * The history is capped at the last 10 messages (5 complete turns).
 */
@RestController
@RequestMapping("/api/asistente")
public class AsistenteController {

    private static final String CLAVE_HISTORIAL = "historialLlm";
    private static final int    MAX_HISTORIAL   = 10;

    private final AgentOrchestrator orquestador;

    public AsistenteController(AgentOrchestrator orquestador) {
        this.orquestador = orquestador;
    }

    /**
     * Processes a user message and returns the assistant's response.
     * The session history is loaded before calling the orchestrator and
     * updated with the new turn (user + assistant) upon completion.
     *
     * @param solicitud JSON body containing the "mensaje" field (and optional "historial")
     * @param sesion    HTTP session of the client, used to persist the conversation history
     * @return HTTP 200 response with the "respuesta" field in JSON
     */
    @PostMapping("/chat")
    public ResponseEntity<ChatResponse> chat(@RequestBody ChatRequest solicitud,
                                             HttpSession sesion) {
        String mensaje = solicitud.getMensaje();

        // Load previous history from the session
        List<Map<String, String>> historial = obtenerHistorialDeSesion(sesion);

        // Generate response by passing the history to the orchestrator
        String respuesta = orquestador.manejarMensaje(mensaje, historial);

        // Add the current turn to the history and save it back to the session
        historial.add(Map.of("role", "user",      "content", mensaje));
        historial.add(Map.of("role", "assistant",  "content", respuesta));
        if (historial.size() > MAX_HISTORIAL) {
            historial.subList(0, historial.size() - MAX_HISTORIAL).clear();
        }
        sesion.setAttribute(CLAVE_HISTORIAL, historial);

        return ResponseEntity.ok(new ChatResponse(respuesta));
    }

    /**
     * Retrieves the LLM conversation history stored in the HTTP session.
     * If it does not exist or the stored value is not of the expected type,
     * returns a mutable empty list ready to receive new entries.
     *
     * @param sesion HTTP session of the client
     * @return Mutable list of messages (may be empty)
     */
    @SuppressWarnings("unchecked")
    private List<Map<String, String>> obtenerHistorialDeSesion(HttpSession sesion) {
        Object almacenado = sesion.getAttribute(CLAVE_HISTORIAL);
        if (almacenado instanceof List) {
            return (List<Map<String, String>>) almacenado;
        }
        return new ArrayList<>();
    }
}
